name: Check step 2, Add feature to release branch

# This step triggers after 1-create-beta-release.yml
# This step sets STEP to 3
# This step closes <details id=2> and opens <details id=3>

# This will run when a change to base.css is pushed to the main branch
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:    
      - release-v1.0
    paths:
      - 'base.css'

permissions:
  contents: write

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/get-current-step.yml

  on_feature_added:
    name: On feature added
    needs: setup

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # 2. The STEP is currently '2'
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ !github.event.repository.is_template 
        && needs.setup.outputs.current_step == 2 }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Update README to close <details id=2>
      # and open <details id=3>
      # and set STEP to '3'
      - name: Update to step 3
        uses: skills/action-update-step@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: 3
  
